import "./globals.scss";
import { SharpSans } from "./styles/fonts";

export const metadata = {
  title: "Daniel Rojas Astood",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={SharpSans.className}>{children}</body>
    </html>
  );
}
